name: Publish Rock
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    uses: ./.github/workflows/build.yaml

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo

      - name: Install yq
        run: |
          sudo snap install yq

      - uses: actions/download-artifact@v4
        with:
          name: charmed-kafka-ui

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Import and push to GHCR
        run: |
          IMAGE_NAME="ghcr.io/canonical/charmed-kafka-ui"
          VERSION=$(yq '.version' rockcraft.yaml)
          BASE=$(yq '(.base|split("@"))[1]' rockcraft.yaml)
          TAG="latest-${BASE}_edge"
          DESCRIPTION=$(yq .description rockcraft.yaml | xargs)

          ROCK_FILE=${{ needs.build.outputs.rock }}

          sudo skopeo --insecure-policy copy \
            oci-archive:${ROCK_FILE} \
            docker-daemon:${IMAGE_NAME}:${TAG}
          
          # Add relevant labels
          echo "FROM ${IMAGE_NAME}:${TAG}" | docker build --label org.opencontainers.image.description="${DESCRIPTION}" --label org.opencontainers.image.revision="${COMMIT_ID}" --label org.opencontainers.image.source="${{ github.repositoryUrl }}" -t "${IMAGE_NAME}:${TAG}" -

          echo "Publishing ${IMAGE_NAME}:${TAG}"          
          docker push ${IMAGE_NAME}:${TAG}
          
          VERSION_TAG="${VERSION}-${BASE}_edge"

          docker tag ${IMAGE_NAME}:${TAG} ${IMAGE_NAME}:${VERSION_TAG}

          echo "Publishing ${IMAGE_NAME}:${VERSION_TAG}"          
          docker push ${IMAGE_NAME}:${VERSION_TAG}
